name: annotation 
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.13
  # - agat==1.4.2
  - samtools==1.21
  - bedtools==2.31.1
  - minimap2==2.29
  - ipykernel==6.29.5
  - nextflow==25.04.2
  - pip
  - pip:
      - jupyterlab==4.4.2
      - matplotlib==3.10.1
      - numpy==2.2.3
      - pandas==2.2.3
      - seaborn==0.13.2
